#4745 refactor withPeerSelectionAction argument list
IntersectMBO/ouroboros-network pull request #4803
Opened 2024-02-12 09:03 UTC by crocodile-dentist

# Description

_description of the pull request, if it fixes a particular issue it should link the PR to a particular issue, see [ref](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)_

# Checklist

- Branch
    - [ ] Updated changelog files.
    - [ ] Commit sequence broadly makes sense
    - [ ] Commits have useful messages
    - [ ] The documentation has been properly updated
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [ ] Reviewer requested

2024-02-12 09:38 UTC, crocodile-dentist commented
issue #4745

2024-02-12 11:17 UTC, coot commented
^ if there's an issue, it's enough to attach it in the `Development` section on the right, no need to add it to the project.

2024-02-12 11:23 UTC, coot commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerSelectionActions.hs
> +    }
Could you also add some haddocks?

2024-02-12 11:39 UTC, coot commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerSelectionActions.hs
> +{-# LANGUAGE RecordWildCards     #-}
Please avoid `RecordWildCards`: it often hides where arguments are coming from and going to, which makes it more difficult to read the code - we try to optimise for reading, not writting.

2024-02-14 11:42 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerSelectionActions.hs
> +    }
Good to know.

2024-02-14 11:43 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/Diffusion/P2P.hs
> +                  PeerSelectionActionTracers {..}
Good to know.

2024-02-14 11:59 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerSelectionActions.hs
>    readLedgerStateJudgement
I've repackaged all arguments into three logical records, minus the continuation ofc.

2024-02-14 11:59 UTC, crocodile-dentist commented on ouroboros-network/CHANGELOG.md
> +
Correct, I've moved the change into breaking section.

2024-02-15 09:12 UTC, coot requested changes
Very nice, a few minor comments.

2024-02-20 10:44 UTC, coot approved these changes
LGTM, thanks @crocodile-dentist.

2024-02-20 10:44 UTC, coot commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerSelectionActions.hs
> +  -- ^ are we there yet?
:smile:
```suggestion
  -- ^ Is consensus close to current slot?
```

2024-02-20 13:13 UTC, merged