Remove the mutex between peer selection and churn governors
IntersectMBO/ouroboros-network pull request #4895
Opened 2024-06-24 18:41 UTC by crocodile-dentist

# Description

Since churn loop code was refactored such that there's only one call site to update the peer targets TVar, it was an easy fix to ensure that the right targets basis was used for the modification.

# Checklist

### Quality
* [ x] Commit sequence makes sense and have useful messages, see [ref][contrib#git-history].
* [ ] New tests are added and existing tests are updated.
* [ ] Self-reviewed the PR.

### Maintenance
* [ ] Linked an [issue][link-issue] or added the PR to the current sprint of [`ouroboros-network`][project] project.
* [ ] Added labels.
* [ ] Updated changelog files.
* [ ] The documentation has been properly updated, see [ref][contrib#documentation].

[project]: https://github.com/orgs/IntersectMBO/projects/5/views/1
[link-issue]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=
[contrib#git-history]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#git-history
[contrib#documentation]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#documentation

2024-06-27 15:01 UTC, bolt12 requested changes
Nice! I would prefer if you squashed this in the commit you introduce the mutex in the first place so it is easier to review and the commit history isn't confusing.

2024-07-01 10:10 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs
> +    increaseEstablishedBigLedgerPeers _ base
No, not for these targets.

2024-07-01 10:11 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs
> +    decreaseEstablishedBigLedgerPeers _ base targets =
Not for these targets.

2024-07-01 10:11 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs
> +    decreaseKnownBigLedgerPeers _ targets base =
Not needed here.

2024-07-01 10:12 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs
> +    increaseKnownPeers _ base targets =
Not needed here.

2024-07-01 10:12 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs
> +    increaseKnownBigLedgerPeers _ base targets =
Not needed here.

2024-07-01 10:14 UTC, crocodile-dentist commented
I've taken your advice and squashed these changes into the appropriate commit.

2024-07-01 10:14 UTC, closed without merging