TxSubmission - add initial delay before requesting transactions
IntersectMBO/ouroboros-network pull request #4930
Opened 2024-08-13 09:48 UTC by crocodile-dentist

# Description

We delay initial request for transactions from a client to conserve network resources in case he disconnects relatively quickly for reasons in the referenced issue.

resolves #4927 

# Checklist

### Quality
* [x] Commit sequence makes sense and have useful messages, see [ref][contrib#git-history].
* [ ] New tests are added and existing tests are updated.
* [ ] Self-reviewed the PR.

### Maintenance
* [ ] Linked an [issue][link-issue] or added the PR to the current sprint of [`ouroboros-network`][project] project.
* [ ] Added labels.
* [ ] Updated changelog files.
* [ ] The documentation has been properly updated, see [ref][contrib#documentation].

[project]: https://github.com/orgs/IntersectMBO/projects/5/views/1
[link-issue]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=
[contrib#git-history]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#git-history
[contrib#documentation]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#documentation

2024-08-13 11:45 UTC, karknu approved these changes
LGTM

2024-08-13 15:48 UTC, coot requested changes

2024-08-13 15:51 UTC, crocodile-dentist commented on ouroboros-network/src/Ouroboros/Network/TxSubmission/Inbound.hs
> +      threadDelay (round @Double . realToFrac . fromMaybe (-1) $ longWait)
But I thought that the client (connecting) can't spam the tx's unless it is requested by the inbound (server)? Looking at io-classes, threadDelay should be in microseconds - I think this is the issue.

2024-08-19 15:52 UTC, coot approved these changes
LGTM

2024-08-20 16:07 UTC, merged